const MAIN = {
    CATCH_ERROR: "CATCH_ERROR",
    CHANGE_CURRENT_PAGE: "CHANGE_CURRENT_PAGE",
    CHANGE_WINDOW_WIDTH: "CHANGE_WINDOW_WIDTH",
};

const POST = {
    LOADING: "LOADING",
    GET_POST_LIST: "GET_POST_LIST",
    CHANGE_POST_LIST: "CHANGE_POST_LIST",
    GET_CURRENT_POST: "GET_CURRENT_POST",
    CHANGE_CURRENT_POST: "CHANGE_CURRENT_POST",
    PUSH_NEW_POST: "PUSH_NEW_POST",
    ADD_NEW_COMMENT: "ADD_NEW_COMMENT",
    SEARCH_POST: "SEARCH_POST",
};

const USER = {
    GET_USERS_LIST: "GET_USERS_LIST",
    GET_USER: "GET_USER",
    LOGOUT: "LOGOUT",
};

export {MAIN, POST, USER};